#!/usr/bin/env bash
set -euo pipefail
AXU5EVB_DRIVER_POST_START_SLEEP_NS=1000 \
AXU5EVB_DRIVER_POLL_SLEEP_NS=1000 \
TEST_DATA_ROOT_PATH=${TEST_DATA_ROOT_PATH:-/tmp/tvm_test_data} \
MPLCONFIGDIR=${MPLCONFIGDIR:-/tmp/mpl} \
PYTHONUNBUFFERED=1 \
  /home/orange/miniconda3/envs/vta-resnet/bin/python \
  /home/orange/code/tvm/vta/tutorials/frontend/deploy_classification_stage_pipeline_native.py \
  --board \
  '' \
  --remote-dir \
  /var/volatile/vta_stage_pipeline_search/buildability_islands_3_6__10_12__13_18 \
  --remote-min-free-mb \
  128 \
  --scheme \
  three_stage_a \
  --scheme-config-json \
  vta/tutorials/frontend/report_out/native_stage_pipeline_searches/20260507_v23_warm100/theory_build100/buildability/scheme_configs/islands_3_6__10_12__13_18.json \
  --candidate-id \
  islands_3_6__10_12__13_18 \
  --vta-islands-json \
  '[{"end_idx": 6, "end_unit": "layer2_block0_skip_proj", "start_idx": 3, "start_unit": "layer1_block1_main_preadd", "unit_names": ["layer1_block1_main_preadd", "layer1_block1_add_relu_tail", "layer2_block0_main_preadd", "layer2_block0_skip_proj"]}, {"end_idx": 12, "end_unit": "layer3_block0_add_relu_tail", "start_idx": 10, "start_unit": "layer3_block0_main_preadd", "unit_names": ["layer3_block0_main_preadd", "layer3_block0_skip_proj", "layer3_block0_add_relu_tail"]}, {"end_idx": 18, "end_unit": "layer4_block1_main_preadd", "start_idx": 13, "start_unit": "layer3_block1_main_preadd", "unit_names": ["layer3_block1_main_preadd", "layer3_block1_add_relu_tail", "layer4_block0_main_preadd", "layer4_block0_skip_proj", "layer4_block0_add_relu_tail", "layer4_block1_main_preadd"]}]' \
  --unit-assignment-json \
  '[{"device": "cpu", "stage": "stage0_cpu", "unit_name": "stem"}, {"device": "cpu", "stage": "stage0_cpu", "unit_name": "layer1_block0_main_preadd"}, {"device": "cpu", "stage": "stage0_cpu", "unit_name": "layer1_block0_add_relu_tail"}, {"device": "vta", "stage": "stage1_vta", "unit_name": "layer1_block1_main_preadd"}, {"device": "vta", "stage": "stage1_vta", "unit_name": "layer1_block1_add_relu_tail"}, {"device": "vta", "stage": "stage1_vta", "unit_name": "layer2_block0_main_preadd"}, {"device": "vta", "stage": "stage1_vta", "unit_name": "layer2_block0_skip_proj"}, {"device": "cpu", "stage": "stage2_cpu", "unit_name": "layer2_block0_add_relu_tail"}, {"device": "cpu", "stage": "stage2_cpu", "unit_name": "layer2_block1_main_preadd"}, {"device": "cpu", "stage": "stage2_cpu", "unit_name": "layer2_block1_add_relu_tail"}, {"device": "vta", "stage": "stage3_vta", "unit_name": "layer3_block0_main_preadd"}, {"device": "vta", "stage": "stage3_vta", "unit_name": "layer3_block0_skip_proj"}, {"device": "vta", "stage": "stage3_vta", "unit_name": "layer3_block0_add_relu_tail"}, {"device": "vta", "stage": "stage4_vta", "unit_name": "layer3_block1_main_preadd"}, {"device": "vta", "stage": "stage4_vta", "unit_name": "layer3_block1_add_relu_tail"}, {"device": "vta", "stage": "stage4_vta", "unit_name": "layer4_block0_main_preadd"}, {"device": "vta", "stage": "stage4_vta", "unit_name": "layer4_block0_skip_proj"}, {"device": "vta", "stage": "stage4_vta", "unit_name": "layer4_block0_add_relu_tail"}, {"device": "vta", "stage": "stage4_vta", "unit_name": "layer4_block1_main_preadd"}, {"device": "cpu", "stage": "stage5_cpu", "unit_name": "layer4_block1_add_relu_tail"}, {"device": "cpu", "stage": "stage5_cpu", "unit_name": "head"}]' \
  --runs \
  20 \
  --queue-depth \
  2 \
  --runtime-num-threads \
  4 \
  --stage-runtime-num-threads \
  3,1,1,1,1,4 \
  --stage-build-cache-dir \
  vta/tutorials/frontend/report_out/native_stage_pipeline_build_cache/v23_20260506/stages \
  --fetch-results-dir \
  vta/tutorials/frontend/report_out/native_stage_pipeline_searches/20260507_v23_warm100/theory_build100/buildability/islands_3_6__10_12__13_18 \
  --vta-runtime-profile-dir \
  profile \
  --vta-runtime-profile-events-limit \
  200 \
  --ssh-command-timeout-s \
  60 \
  --scp-timeout-s \
  600 \
  --serial-timeout-s \
  180 \
  --pipeline-timeout-s \
  180 \
  --fetch-timeout-s \
  120 \
  --correctness-policy \
  exact \
  --run-serial-before-pipeline \
  --no-ssh-control-master \
  --package-only \
  --build-dir \
  vta/tutorials/frontend/report_out/native_stage_pipeline_build_cache/v23_20260506/buildability/islands_3_6__10_12__13_18 \
  --keep-build-dir \
  --compare-serial-pipeline \
  --image-size \
  224
